CREATE SCHEMA IF NOT EXISTS app;

CREATE TYPE app.order_status AS ENUM ('pending', 'paid', 'fulfilled');

CREATE SEQUENCE app.order_numbers AS bigint
    INCREMENT BY 10
    MINVALUE 1
    START WITH 1
    CACHE 1
    NO CYCLE;

CREATE TABLE app.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_code text NOT NULL,
    status app.order_status NOT NULL DEFAULT 'pending',
    quantity bigint NOT NULL DEFAULT 2,
    unit_price_cents bigint NOT NULL,
    note text NOT NULL DEFAULT 'new',
    category text NOT NULL DEFAULT 'general',
    total_cents bigint GENERATED ALWAYS AS (quantity * unit_price_cents) STORED,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT orders_quantity_check CHECK (quantity > 0)
);

CREATE TABLE app.order_audit (
    order_id bigint NOT NULL,
    observed_note text NOT NULL
);

CREATE INDEX orders_status_idx
    ON app.orders (lower(order_code))
    WHERE status = 'pending';

CREATE VIEW app.order_summary AS
    SELECT id, order_code, status, quantity, category, total_cents
      FROM app.orders;

CREATE FUNCTION app.calculate_total(quantity bigint, unit_price_cents bigint)
    RETURNS bigint
    AS 'SELECT quantity * unit_price_cents'
    LANGUAGE SQL IMMUTABLE;

CREATE PROCEDURE app.update_order_note(order_id bigint, new_note text)
    LANGUAGE PLpgSQL AS $$
BEGIN
    UPDATE app.orders
       SET note = new_note
     WHERE orders.id = order_id;
END
$$;

CREATE FUNCTION app.audit_order_update() RETURNS trigger AS $$
BEGIN
    INSERT INTO app.order_audit(order_id, observed_note)
    VALUES ((NEW).id, (NEW).note);
    RETURN NEW;
END
$$ LANGUAGE PLpgSQL;

CREATE TRIGGER orders_audit
    AFTER UPDATE ON app.orders
    FOR EACH ROW EXECUTE FUNCTION app.audit_order_update();
